"""Add conformity score to user

Revision ID: 693ae413e688
Revises: 1703043bec54
Create Date: 2026-05-10 21:37:02.239156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693ae413e688'
down_revision = '1703043bec54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conformity_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('conformity_score')

    # ### end Alembic commands ###
