"""Add access code to Debate

Revision ID: 698cac10eaa6
Revises: 693ae413e688
Create Date: 2026-05-10 22:07:27.708679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698cac10eaa6'
down_revision = '693ae413e688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debate', schema=None) as batch_op:
        batch_op.drop_column('access_code')

    # ### end Alembic commands ###
